languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = ""
canonifyurls = true
title = "Shubham Saxena"
author = "Shubham Saxena"
theme = "pixyll"
disqusShortname = "shubham7saxena7"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  google_analytics_id = "G-MFSL63BKCB"
  twitter_username = "saxena_shubham7"